"""
finance_templates.py — 30 MSME-specific financial query templates.
Each template drives the NL→SQL matching in llm_engine.py.
"""

TEMPLATES = [
    # ── CATEGORY 1: CASH FLOW ────────────────────────────────────────────────
    {
        "id": "monthly_net_cashflow",
        "category": "cash_flow",
        "triggers": ["cash flow", "monthly cash", "net cash", "paisa", "cash position"],
        "nl_variants": ["What is my monthly cash flow?", "Show my net cash each month", "Har mahine kitna paisa bachta hai?"],
        "sql_template": "SELECT strftime('%Y-%m', date) as month, ROUND(SUM(credit) - SUM(debit), 0) as net_flow FROM {table} GROUP BY month ORDER BY month",
        "result_format": "currency",
        "insight_prefix": "Your monthly net cash flow is",
    },
    {
        "id": "cash_crunch_forecast",
        "category": "cash_flow",
        "triggers": ["cash crunch", "run out", "runway", "kitne din", "how many days", "when will money run out"],
        "nl_variants": ["When will I run out of money?", "How many days of runway do I have?", "Kitne din ka paisa bacha hai?"],
        "sql_template": "SELECT ROUND(AVG(daily_burn), 0) as avg_daily_burn FROM (SELECT date, SUM(debit) as daily_burn FROM {table} GROUP BY date) burns",
        "result_format": "days",
        "insight_prefix": "Your estimated cash runway is",
    },
    {
        "id": "largest_expenses",
        "category": "cash_flow",
        "triggers": ["biggest expense", "largest payment", "sabse bada kharch", "top spending", "where is money going"],
        "nl_variants": ["What are my biggest expenses?", "Where is most of my money going?", "Sabse bada kharch kya hai?"],
        "sql_template": "SELECT description, ROUND(SUM(debit), 0) as total FROM {table} WHERE debit > 0 GROUP BY description ORDER BY total DESC LIMIT 10",
        "result_format": "currency",
        "insight_prefix": "Your largest expense category is",
    },
    {
        "id": "weekly_cashflow_trend",
        "category": "cash_flow",
        "triggers": ["weekly", "this week", "last week", "week trend", "hafte ka"],
        "nl_variants": ["Show my weekly cash flow", "What happened this week?", "Hafte mein kitna aaya gaya?"],
        "sql_template": "SELECT strftime('%Y-%W', date) as week, ROUND(SUM(credit), 0) as inflow, ROUND(SUM(debit), 0) as outflow, ROUND(SUM(credit) - SUM(debit), 0) as net FROM {table} GROUP BY week ORDER BY week DESC LIMIT 8",
        "result_format": "currency",
        "insight_prefix": "Your weekly cash flow trend shows",
    },
    {
        "id": "balance_trend",
        "category": "cash_flow",
        "triggers": ["balance", "bank balance", "kitna bacha", "remaining balance", "account balance"],
        "nl_variants": ["What is my bank balance trend?", "Show my balance over time", "Mere account mein kitna bacha?"],
        "sql_template": "SELECT date, ROUND(balance, 0) as balance FROM {table} WHERE balance > 0 ORDER BY date DESC LIMIT 30",
        "result_format": "currency",
        "insight_prefix": "Your bank balance trend shows",
    },
    {
        "id": "worst_months",
        "category": "cash_flow",
        "triggers": ["worst month", "bad month", "loss month", "lowest revenue", "sabse bura"],
        "nl_variants": ["Which were my worst months?", "When did I make the least money?", "Sabse bura mahina kaun sa tha?"],
        "sql_template": "SELECT strftime('%Y-%m', date) as month, ROUND(SUM(credit) - SUM(debit), 0) as net_flow FROM {table} GROUP BY month ORDER BY net_flow ASC LIMIT 3",
        "result_format": "currency",
        "insight_prefix": "Your worst performing months were",
    },

    # ── CATEGORY 2: REVENUE ANALYSIS ─────────────────────────────────────────
    {
        "id": "monthly_revenue",
        "category": "revenue",
        "triggers": ["revenue", "income", "earnings", "kamai", "monthly income", "total income"],
        "nl_variants": ["What is my monthly revenue?", "Show my income each month", "Har mahine kitni kamai hui?"],
        "sql_template": "SELECT strftime('%Y-%m', date) as month, ROUND(SUM(credit), 0) as revenue FROM {table} GROUP BY month ORDER BY month",
        "result_format": "currency",
        "insight_prefix": "Your monthly revenue is",
    },
    {
        "id": "revenue_growth_rate",
        "category": "revenue",
        "triggers": ["growth", "growing", "revenue growth", "kitna badha", "growth rate"],
        "nl_variants": ["How fast is my revenue growing?", "What is my growth rate?", "Revenue kitna badh raha hai?"],
        "sql_template": "WITH monthly AS (SELECT strftime('%Y-%m', date) as month, SUM(credit) as rev FROM {table} GROUP BY month) SELECT month, ROUND(rev, 0) as revenue, ROUND(LAG(rev) OVER (ORDER BY month), 0) as prev_month, ROUND((rev - LAG(rev) OVER (ORDER BY month)) / LAG(rev) OVER (ORDER BY month) * 100, 1) as growth_pct FROM monthly ORDER BY month",
        "result_format": "percentage",
        "insight_prefix": "Your average monthly revenue growth rate is",
    },
    {
        "id": "best_revenue_month",
        "category": "revenue",
        "triggers": ["best month", "highest revenue", "sabse accha", "peak month", "record month"],
        "nl_variants": ["Which was my best month?", "When did I earn the most?", "Sabse accha mahina kaun sa tha?"],
        "sql_template": "SELECT strftime('%Y-%m', date) as month, ROUND(SUM(credit), 0) as revenue FROM {table} GROUP BY month ORDER BY revenue DESC LIMIT 1",
        "result_format": "currency",
        "insight_prefix": "Your best revenue month was",
    },
    {
        "id": "revenue_vs_expenses",
        "category": "revenue",
        "triggers": ["revenue vs", "income vs expense", "profit", "margin", "net margin"],
        "nl_variants": ["What is my profit margin?", "Revenue vs expenses comparison", "Kitna profit ho raha hai?"],
        "sql_template": "SELECT strftime('%Y-%m', date) as month, ROUND(SUM(credit), 0) as revenue, ROUND(SUM(debit), 0) as expenses, ROUND(SUM(credit) - SUM(debit), 0) as profit, ROUND((SUM(credit) - SUM(debit)) / SUM(credit) * 100, 1) as margin_pct FROM {table} GROUP BY month ORDER BY month",
        "result_format": "currency",
        "insight_prefix": "Your profit margin is",
    },
    {
        "id": "average_transaction_size",
        "category": "revenue",
        "triggers": ["average transaction", "typical payment", "average sale", "transaction size"],
        "nl_variants": ["What is my average transaction size?", "How much is a typical payment?"],
        "sql_template": "SELECT ROUND(AVG(CASE WHEN credit > 0 THEN credit END), 0) as avg_inflow, ROUND(AVG(CASE WHEN debit > 0 THEN debit END), 0) as avg_outflow, COUNT(CASE WHEN credit > 0 THEN 1 END) as inflow_count, COUNT(CASE WHEN debit > 0 THEN 1 END) as outflow_count FROM {table}",
        "result_format": "currency",
        "insight_prefix": "Your average inflow transaction size is",
    },
    {
        "id": "large_transactions",
        "category": "revenue",
        "triggers": ["large transaction", "big payment", "bada transaction", "over 1 lakh", "high value"],
        "nl_variants": ["Show me large transactions", "What payments were over 1 lakh?", "Bade transactions kaun se the?"],
        "sql_template": "SELECT date, description, ROUND(credit, 0) as credit, ROUND(debit, 0) as debit FROM {table} WHERE credit > 100000 OR debit > 100000 ORDER BY date DESC",
        "result_format": "currency",
        "insight_prefix": "Your high-value transactions include",
    },

    # ── CATEGORY 3: RECEIVABLES & PAYABLES ───────────────────────────────────
    {
        "id": "overdue_receivables",
        "category": "receivables",
        "triggers": ["overdue", "pending payment", "baaki", "who owes", "receivable", "unpaid"],
        "nl_variants": ["Who owes me money?", "Show overdue receivables", "Kisne paisa nahi diya?"],
        "sql_template": "SELECT description, ROUND(SUM(credit), 0) as expected, MAX(date) as last_seen FROM {table} WHERE credit > 0 GROUP BY description ORDER BY expected DESC LIMIT 10",
        "result_format": "currency",
        "insight_prefix": "Your pending receivables show",
    },
    {
        "id": "days_sales_outstanding",
        "category": "receivables",
        "triggers": ["DSO", "days sales", "collection period", "payment days", "kitne din mein milta"],
        "nl_variants": ["What is my DSO?", "How long to collect payments?", "Kitne din mein payment milti hai?"],
        "sql_template": "SELECT ROUND(AVG(CAST(julianday('now') - julianday(date) AS REAL)), 0) as avg_days_outstanding, COUNT(*) as inflow_count FROM {table} WHERE credit > 0",
        "result_format": "days",
        "insight_prefix": "Your average collection period is",
    },
    {
        "id": "supplier_payments",
        "category": "receivables",
        "triggers": ["supplier", "vendor", "payment to", "kise diya", "vendor payment"],
        "nl_variants": ["Who am I paying the most?", "Show supplier payments", "Kise kitna diya?"],
        "sql_template": "SELECT description, COUNT(*) as frequency, ROUND(SUM(debit), 0) as total_paid, ROUND(AVG(debit), 0) as avg_payment FROM {table} WHERE debit > 0 GROUP BY description ORDER BY total_paid DESC LIMIT 10",
        "result_format": "currency",
        "insight_prefix": "Your top supplier/vendor payments go to",
    },
    {
        "id": "payment_regularity",
        "category": "receivables",
        "triggers": ["regular payment", "consistent", "on time", "payment pattern", "recurring"],
        "nl_variants": ["Which payments are regular?", "Show recurring transactions", "Kaunse payments regular hain?"],
        "sql_template": "SELECT description, COUNT(*) as payment_count, MIN(date) as first_payment, MAX(date) as last_payment, ROUND(AVG(debit), 0) as avg_amount FROM {table} WHERE debit > 0 GROUP BY description HAVING payment_count > 2 ORDER BY payment_count DESC LIMIT 10",
        "result_format": "currency",
        "insight_prefix": "Your most regular payment patterns are",
    },
    {
        "id": "working_capital",
        "category": "receivables",
        "triggers": ["working capital", "working capital gap", "short term", "capital chahiye", "fund the gap"],
        "nl_variants": ["What is my working capital position?", "Do I have enough working capital?", "Working capital kitna hai?"],
        "sql_template": "SELECT ROUND(SUM(CASE WHEN credit > 0 THEN credit ELSE 0 END), 0) as total_inflow, ROUND(SUM(CASE WHEN debit > 0 THEN debit ELSE 0 END), 0) as total_outflow, ROUND(SUM(credit) - SUM(debit), 0) as working_capital FROM {table} WHERE date >= date('now', '-90 days')",
        "result_format": "currency",
        "insight_prefix": "Your 90-day working capital position is",
    },

    # ── CATEGORY 4: RISK SIGNALS ─────────────────────────────────────────────
    {
        "id": "declining_revenue_alert",
        "category": "risk",
        "triggers": ["declining", "falling revenue", "revenue drop", "gir raha", "revenue fell"],
        "nl_variants": ["Is my revenue declining?", "Show revenue trend last 3 months", "Revenue gir raha hai kya?"],
        "sql_template": "SELECT strftime('%Y-%m', date) as month, ROUND(SUM(credit), 0) as revenue FROM {table} GROUP BY month ORDER BY month DESC LIMIT 3",
        "result_format": "currency",
        "insight_prefix": "Your recent revenue trend shows",
    },
    {
        "id": "high_expense_months",
        "category": "risk",
        "triggers": ["high expense", "overspending", "zyada kharch", "expense spike", "spending too much"],
        "nl_variants": ["Which months did I overspend?", "Show high expense months", "Kab zyada kharch hua?"],
        "sql_template": "SELECT strftime('%Y-%m', date) as month, ROUND(SUM(debit), 0) as expenses FROM {table} GROUP BY month ORDER BY expenses DESC LIMIT 5",
        "result_format": "currency",
        "insight_prefix": "Your highest expense months were",
    },
    {
        "id": "cash_flow_negative_months",
        "category": "risk",
        "triggers": ["negative cash flow", "loss months", "ghata", "negative months", "in the red"],
        "nl_variants": ["Which months had negative cash flow?", "When was I in loss?", "Kab ghata hua?"],
        "sql_template": "SELECT strftime('%Y-%m', date) as month, ROUND(SUM(credit) - SUM(debit), 0) as net_flow FROM {table} GROUP BY month HAVING net_flow < 0 ORDER BY net_flow ASC",
        "result_format": "currency",
        "insight_prefix": "Your negative cash flow months were",
    },
    {
        "id": "transaction_frequency_drop",
        "category": "risk",
        "triggers": ["transaction drop", "less activity", "slow month", "quiet period", "business slow"],
        "nl_variants": ["Is business slowing down?", "Show monthly transaction count", "Transactions kam ho gaye?"],
        "sql_template": "SELECT strftime('%Y-%m', date) as month, COUNT(*) as transaction_count FROM {table} GROUP BY month ORDER BY month DESC LIMIT 6",
        "result_format": "count",
        "insight_prefix": "Your monthly transaction volume shows",
    },
    {
        "id": "balance_below_threshold",
        "category": "risk",
        "triggers": ["low balance", "balance warning", "kam balance", "below 50000", "danger zone"],
        "nl_variants": ["When was my balance dangerously low?", "Show days with low balance", "Balance kab bahut kam tha?"],
        "sql_template": "SELECT date, ROUND(balance, 0) as balance FROM {table} WHERE balance < 50000 AND balance > 0 ORDER BY date DESC LIMIT 10",
        "result_format": "currency",
        "insight_prefix": "Your balance dropped below ₹50K on",
    },
    {
        "id": "unusual_large_debit",
        "category": "risk",
        "triggers": ["unusual", "suspicious", "unexpected expense", "achanak", "outlier", "anomaly"],
        "nl_variants": ["Are there any unusual expenses?", "Show unexpected large payments", "Koi achanak bada payment?"],
        "sql_template": "SELECT date, description, ROUND(debit, 0) as debit FROM {table} WHERE debit > (SELECT AVG(debit) * 3 FROM {table} WHERE debit > 0) ORDER BY debit DESC LIMIT 5",
        "result_format": "currency",
        "insight_prefix": "Unusual large debits detected",
    },

    # ── CATEGORY 5: BUSINESS HEALTH SUMMARY ──────────────────────────────────
    {
        "id": "full_financial_summary",
        "category": "summary",
        "triggers": ["summary", "overview", "full picture", "sab batao", "complete report", "show all", "everything"],
        "nl_variants": ["Give me a financial summary", "Show everything", "Sab kuch batao"],
        "sql_template": "SELECT COUNT(*) as total_transactions, ROUND(SUM(credit), 0) as total_inflow, ROUND(SUM(debit), 0) as total_outflow, ROUND(SUM(credit) - SUM(debit), 0) as net_position, MIN(date) as from_date, MAX(date) as to_date FROM {table}",
        "result_format": "currency",
        "insight_prefix": "Your overall financial position shows",
    },
    {
        "id": "this_month_vs_last_month",
        "category": "summary",
        "triggers": ["this month", "last month", "compare month", "is mahine", "month comparison"],
        "nl_variants": ["How does this month compare to last?", "This month vs last month", "Is mahine vs pichle mahine"],
        "sql_template": "SELECT strftime('%Y-%m', date) as month, ROUND(SUM(credit), 0) as inflow, ROUND(SUM(debit), 0) as outflow, ROUND(SUM(credit) - SUM(debit), 0) as net FROM {table} WHERE date >= date('now', '-60 days') GROUP BY month ORDER BY month DESC",
        "result_format": "currency",
        "insight_prefix": "Month-over-month comparison shows",
    },
    {
        "id": "quarterly_performance",
        "category": "summary",
        "triggers": ["quarter", "quarterly", "3 months", "teen mahine", "Q1", "Q2", "Q3", "Q4"],
        "nl_variants": ["Show quarterly performance", "How was this quarter?", "Teenhine ka hisab batao"],
        "sql_template": "SELECT 'Q' || CAST((CAST(strftime('%m', date) AS INT) + 2) / 3 AS TEXT) || '-' || strftime('%Y', date) as quarter, ROUND(SUM(credit), 0) as revenue, ROUND(SUM(debit), 0) as expenses, ROUND(SUM(credit) - SUM(debit), 0) as profit FROM {table} GROUP BY quarter ORDER BY quarter DESC LIMIT 4",
        "result_format": "currency",
        "insight_prefix": "Your quarterly performance shows",
    },
    {
        "id": "loan_eligibility_signals",
        "category": "summary",
        "triggers": ["loan eligible", "loan le sakta", "credit eligible", "qualify for loan", "loan amount"],
        "nl_variants": ["Am I eligible for a loan?", "How much loan can I get?", "Loan mil sakta hai?"],
        "sql_template": "SELECT ROUND(AVG(monthly_rev), 0) as avg_monthly_revenue, ROUND(MIN(monthly_rev), 0) as worst_month, COUNT(*) as months_of_data, ROUND(AVG(monthly_rev) * 5, 0) as estimated_max_loan FROM (SELECT strftime('%Y-%m', date) as month, SUM(credit) as monthly_rev FROM {table} GROUP BY month)",
        "result_format": "currency",
        "insight_prefix": "Based on your financials, estimated loan eligibility is",
    },

    # ── CATEGORY 6: SEASONAL ANALYSIS ────────────────────────────────────────
    {
        "id": "seasonal_pattern",
        "category": "seasonal",
        "triggers": ["seasonal", "festival", "diwali", "season", "peak season", "which month best"],
        "nl_variants": ["What is my seasonal pattern?", "Which months are strongest?", "Kaunsa season best hai?"],
        "sql_template": "SELECT strftime('%m', date) as month_num, ROUND(AVG(monthly_rev), 0) as avg_revenue FROM (SELECT strftime('%Y-%m', date) as ym, strftime('%m', date) as month, SUM(credit) as monthly_rev FROM {table} GROUP BY ym) GROUP BY month_num ORDER BY month_num",
        "result_format": "currency",
        "insight_prefix": "Your seasonal revenue pattern shows",
    },
    {
        "id": "year_over_year",
        "category": "seasonal",
        "triggers": ["year over year", "YoY", "last year", "pichhle saal", "annual growth", "yearly"],
        "nl_variants": ["How did I do vs last year?", "Year over year comparison", "Pichhle saal se comparison"],
        "sql_template": "SELECT strftime('%Y', date) as year, ROUND(SUM(credit), 0) as annual_revenue, ROUND(SUM(debit), 0) as annual_expenses, ROUND(SUM(credit) - SUM(debit), 0) as annual_profit FROM {table} GROUP BY year ORDER BY year",
        "result_format": "currency",
        "insight_prefix": "Your year-over-year performance shows",
    },
    {
        "id": "cash_conversion_cycle",
        "category": "seasonal",
        "triggers": ["cash conversion", "CCC", "how fast convert", "convert to cash", "kitne din mein aata"],
        "nl_variants": ["What is my cash conversion cycle?", "How quickly do I collect cash?", "Payment kitne din mein aata hai?"],
        "sql_template": "SELECT ROUND(AVG(CAST(julianday('now') - julianday(date) AS REAL)), 0) as avg_receivable_days, COUNT(*) as total_inflows, ROUND(SUM(credit), 0) as total_received FROM {table} WHERE credit > 0",
        "result_format": "days",
        "insight_prefix": "Your cash conversion cycle averages",
    },
]

# Fast lookup by template id
TEMPLATE_MAP = {t["id"]: t for t in TEMPLATES}
